### ISSUE TITLE
App funcional sin la necesidad de loguearse

### ISSUE THREAD

**Issue by santisemhan** [pybalt/fainmap#13]
Estaria bueno que no sea necesario loguearse. Si no te logueas podria guardarse la información en el local storage.

**Comment by pybalt** [comment]
No podrías usar la app cross-platform / estarías atado a un solo dispositivo

**Comment by santisemhan** [comment]
Si, pero bueno ya eso depende del usuario. Yo tenia ganas de usar la app pero no de registrarme. Se podria avisar que no se van a guardar los cambios en otros dispositivos si no te logueas.

**Comment by santisemhan** [comment]
https://www.nngroup.com/articles/checklist-registration-login/

**Comment by pybalt** [comment]
> Si, pero bueno ya eso depende del usuario. Yo tenia ganas de usar la app pero no de registrarme. _**Se podria avisar que no se van a guardar los cambios en otros dispositivos si no te logueas.**_

Tomo la solución híbrida. En la proxima iteración quito el login y sumo el aviso de que el cross-origin necesita registar LU.

---

**Respecto del link que enviaste**, no hay passwords que memorizar más allá del LU. El mail es para prevenir que otros usuarios usen la app.

_**Do not ask users to confirm their registration through email.
Switching applications can disorient users and can raise roadblocks that ultimately may prevent them from attaining their original goal (which is never to register on your site). If you must confirm credentials, do so by sending users a code in a text message instead of a link through email, because that code will be easier to type without switching contexts, just by glancing at the notification displayed at the top of the screen.**_

Es justamente lo que estoy desarrollando. Vi algunos usuarios que se registraron con numeros genericos como "000" o mails "a@uade.edu.ar". El problema es si a varios se les ocurre la misma idea, van a tener un "race condition" y arruinando su propia experiencia.

**Comment by santisemhan** [comment]
Exacto, al dejar la opción de no tener que loguearte es muy probable que deje de pasar lo de emails falsos. Pero si, concuerdo con vos, con el link que deje no estoy de acuerdo con todo pero pense que te serviria para la toma de desiciones. Saludos!
